### ISSUE TITLE
Why does this test suite distinguish between credentials and presentations?

### ISSUE THREAD

**Issue by peacekeeper** [decentralized-identity/JWS-Test-Suite#10]
Shouldn't the process of adding a JsonWebSignature2020 be the same for a credential or a presentation or any other JSON-LD document?

Or does this test suite really test two separate things, i.e. 1. adding a JsonWebSignature2020, and 2. something else that's specific to credentials/presentations?

**Comment by OR13** [comment]
See the latest report, when verifying a presentation the proof is expected to be associated with `authentication` not `assertionMethod`.

Many implementations will handle validation for the input differently depending on if its a VC or a VP being requested, short list of potential issues:

1. does the presentation (input to a VP) already contain a proof?
2. does the VP contain no proof and no credentials?
3. does the VP use the wrong proofPurpose (assertionMethod instead of authentication)

typically you want to handle some of these issues before you even hit a cryptographic layer...

1. validate untrusted user input (ideally by conformance to schema or spec).
2. construct output from inputs.

In the case of verify, we are validating the input, which was an output of a previous step.

so for example, no need to attempt to verify a JSON object without a proof, or with a malformed one.

The same is true of vanilla JOSE... if the header is malformed, you don't need to bother checking the signature...

If the header uses the wrong `alg` (say ECDH-ES+A256KW for a JWS) you don't need to bother trying to verify that.

**Comment by OR13** [comment]
To answer your main question though, this suit is for testing the VC Data Model proof formats that rely on JWS, which means allowing an implementation to show conformance for both VCs and VPS... Similar to how a JOSE implementation might allow you to show conformance too JWS and JWT.

**Comment by peacekeeper** [comment]
Hmm I think this contradicts a bit your testing philosophy which you've articulated a few times, i.e. that test suites should be focused on something very specific, and not cause additional headache for implementers.

When I initially looked at this test suite, I expected that it simply tests the validity of the JsonWebSignature2020 on the JSON-LD document, not some extra VC/VP/DID specific things.

Anyway, I have not problem with it now that I understand, thanks for explaining!

**Comment by peacekeeper** [comment]
For example, since there are apparently several things to consider, I have no idea why our implementation shows "pass" for Credentials, but "fail" for Presentations: https://identity.foundation/JWS-Test-Suite/#danubetech

What exactly failed?

**Comment by OR13** [comment]
```
{
"@context": [
"https://www.w3.org/2018/credentials/v1",
"https://w3id.org/security/suites/jws-2020/v1"
],
"type": [
"VerifiablePresentation"
],
"proof": {
"type": "JsonWebSignature2020",
"created": "2021-10-02T19:44:36Z",
"proofPurpose": "assertionMethod",
"verificationMethod": "did:example:123#key-0",
"jws": "eyJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdLCJhbGciOiJFZERTQSJ9..iWNU2RrEPXzbhM8nG5hbW7PuY5cBjUm0WqSGCLGuTlsRpGRKgoR-ttOvHJTYcFjiQNSM7gxW9dFC7JGJyo_GCg"
}
}
```

**"proofPurpose": "assertionMethod",**

This should be `authentication`.

**Comment by OR13** [comment]
Put another way, should being able to add an assertionMethod key to a did document allow me to authenticate?

**Comment by OR13** [comment]
@peacekeeper yes, i think `challenge` is required, but `domain` is not.

**Comment by peacekeeper** [comment]
Okay thanks. I'm fine with closing this issue, unless you'd like to leave it open for others to see.
