### ISSUE TITLE
RSA Implementation Should Not Check For "Holder" Property in VPs

### ISSUE THREAD

**Issue by decentralgabe** [decentralized-identity/JWS-Test-Suite#52]
https://github.com/decentralized-identity/JWS-Test-Suite/pull/49#issuecomment-1063050687

All implementations that do not include the `holder` property in VPs seem to fail. This should be dropped from verification correctness. 

cc: @clehner @OR13

**Comment by decentralgabe** [comment]
> The ssi library could be updated to support VPs without holder property in a general way. (More about that below).
this makes sense to me

> It's true that the holder property is optional. I guess I thought that without it, one would have a "presentation", rather than a "verifiable presentation".

why? what if the proof is signed by a `verificationMethod` which contains a `did` that matches the `did` and/or `verificationMethod` of the listed credentials? wouldn't that be a verifiable presentation?

> The example keypair and DID are not provided as arguments to the verify command/function. Should these be hard-coded in the verifier? 

the key used to verify needs to match the provided `verificationMethod` in that respect, perhaps it should be an argument. Our impl parses out the signing key from the test file name, and loads that independently. We do take the parameter.

> maybe it would be equivalent for this test suite to simply allow any proof to verify

I guess I'd back up and ask what the point of the test suite is. are we verifying signing implementations, or the combination of signing implementations against a standard which may have its own nuances? I think there's a middle ground -- i.e. the Transmute impl fails if a `challenge` property is not present on VPs, and this makes sense. That's not exactly in the spec either.

I find it weird to add properties to data _before signing_, which is why our impl does not add the `holder` property that's not present.

So...I guess to summarize:
- I agree with your thinking, generally
- I believe there are two paths forward.... (a) say that we don't need a holder property to verify, given the proof/signature checks out. (b) say that a holder property is required for validation, and update the first test case to include one

wdyt? @OR13 ?

**Comment by OR13** [comment]
Per the spec, a VP only requires `@context` and `type`... any additional requirements enforced by an implementation are "bugs" imo... adding required fields that the spec does not list as required causes problems with interoperability.

There are a few issues with VPs, that should probably be tracked separately, but I will list them all here first.

1. `holder` is optional
2. in JSON-LD, proof.domain is optional and chosen by the "holder" even if they are not present.
3. in JSON-LD, proof.challenge is required and chosen by the "verifier" 
4. if present, `domain` is mapped to `aud` and `challenge` is mapped to `nonce` in the JWT variant of a VC.
5. `sub` is optional in a VP-JWT, because of point 1.
6. in JSON-LD, proofPurpose for a VP is `authentication`
7. in JSON-LD, `verificationMethod` for a VP is expected to be in the `authentication` section of the did document
8. in VP-JWT, its strongly recommended that `kid` look like `verificationMethod` and that it be in the `authentication` section of the did document

If Transmute's implementation violates any of these things we consider that a bug... we know we have at least a problem with the holder being treated as required.

**Comment by decentralgabe** [comment]
Fixed in https://github.com/decentralized-identity/JWS-Test-Suite/pull/55
